[package]
name = "asn-win-wgpu"
version = "0.1.0"
edition = "2024"
authors = ["Amberskynet Team"]
description = "Modern window system implementation using Winit + WGPU"
license = "MIT"
repository = "https://github.com/amberskynet/asn-win-wgpu"
keywords = ["wgpu", "winit", "graphics", "window", "rendering"]
categories = ["rendering", "gui"]

[workspace]
resolver = "2"

[workspace.dependencies]
tokio = { version = "1.47", features = ["full"] }

[dependencies]
asn-logger = { git = "https://github.com/amberskynet/asn-logger.git", tag = "3.0.0", features = [] }
asn-core = { path = "./modules/asn-core" }
asn-core-bus = { path = "./modules/asn-core-bus" }
asn-gui-core = { path = "./modules/asn-gui-core" }
asn-wgpu = { path = "./modules/asn-wgpu" }
asn-winit = { path = "./modules/asn-winit" }
wgpu-map = { path = "./modules/gui-elements/wgpu-map" }
tokio-bus = { path = "./modules/tokio-bus"}
pollster = "0.4"

[profile.dev]
opt-level = 0
debug = true

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
